### ISSUE TITLE
What is latest way to add bblocks?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/bblocks#14]
@avillar @rob-metalinkage @doublebyte1 My various changes (still not complete) to finish adding some CoverageJSON bblock fragments is very out of date for the re-structured repo. Not clear what is the best way to proceed.

**Comment by rob-metalinkage** [comment]
https://github.com/opengeospatial/bblock-template  has the instructions 

This is in beta,  however I can confirm the validation tooling can be run locally.

So you start to pull the metadata and examples out of asciidocs and get it validating and building, then submit it for re-registration which will update as a git sub-module, and be fully integrated into a ci/ct/cd environment.  

Json-ld contexts can be added to support annotated schemas, if things break without a context (if so thats a bug) a stub can be used.

**Comment by avillar** [comment]
I've created a little [CONTRIBUTING.md](https://github.com/opengeospatial/bblocks/blob/master/CONTRIBUTING.md) file that's basically your comment, @rob-metalinkage .
