### ISSUE TITLE
List of Implementation Standards as of 2024-01-26

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/bblocks#18]
The following list has been obtained from https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/docs/docs.ttl

It was obtained using the query:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub <http://www.opengis.net/def/metamodel/ogc-na/doctype> <http://www.opengis.net/def/doc-type/is> .
  ?sub <http://www.w3.org/2004/02/skos/core#prefLabel> ?prefLabel .
  ?sub <http://purl.org/dc/terms/created> ?created .
} 
ORDER BY DESC(?created)
LIMIT 2000
```
We will use the list to keep track of which Implementation Standards, approved up to the end of 2023, have been broken down into building blocks.

- [ ] 1. http://www.opengis.net/def/docs/22-022r1 OGC SensorThings API Extension: STAplus 1.0 , created 2023-09-23
- [ ] 2. http://www.opengis.net/def/docs/22-049r1 OGC Geospatial eXtensible Access Control Markup Language (GeoXACML) 3.0 , created 2023-09-21
- [ ] 3. http://www.opengis.net/def/docs/22-050r1 OGC Geospatial eXtensible Access Control Markup Language (GeoXACML) 3.0 JSON Profile v1.0 , created 2023-09-21
- [ ] 4. http://www.opengis.net/def/docs/23-008r3 OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 1: Conceptual Model Standard , created 2023-09-19
- [ ] 5. http://www.opengis.net/def/docs/21-056r11 OGC GeoPose 1.0 Data Exchange Standard , created 2023-09-08
- [ ] 6. http://www.opengis.net/def/docs/19-086r6 OGC API - Environmental Data Retrieval Standard , created 2023-07-27
- [ ] 7. http://www.opengis.net/def/docs/21-026 OGC Cloud Optimized GeoTIFF Standard , created 2023-07-14
- [ ] 8. http://www.opengis.net/def/docs/15-042r6 OGC TimeseriesML 1.3 ‚Äì XML Encoding of the Timeseries Profile of Observations and Measurements , created 2023-06-21
- [ ] 9. http://www.opengis.net/def/docs/21-006r2 OGC City Geography Markup Language (CityGML) Part 2: GML Encoding Standard , created 2023-06-20
- [ ] 10. http://www.opengis.net/def/docs/19-072 OGC API - Common - Part 1: Core , created 2023-03-28
- [ ] 11. http://www.opengis.net/def/docs/20-057 OGC API - Tiles - Part 1: Core , created 2022-11-10
- [ ] 12. http://www.opengis.net/def/docs/21-057 OGC GeoPackage WKT for Coordinate Reference Systems Extension , created 2022-10-14
- [ ] 13. http://www.opengis.net/def/docs/17-083r4 OGC Two Dimensional Tile Matrix Set and Tile Set Metadata , created 2022-09-09
- [ ] 14. http://www.opengis.net/def/docs/19-086r5 OGC API - Environmental Data Retrieval Standard , created 2022-08-05
- [ ] 15. http://www.opengis.net/def/docs/17-069r4 OGC API - Features - Part 1: Core corrigendum , created 2022-05-11
- [ ] 16. http://www.opengis.net/def/docs/18-058r1 OGC API - Features - Part 2: Coordinate Reference Systems by Reference corrigendum , created 2022-05-11
- [ ] 17. http://www.opengis.net/def/docs/17-066r2 OGC GeoPackage Extension for Tiled Gridded Coverage Data , created 2022-05-02
- [ ] 18. http://www.opengis.net/def/docs/18-062r2 OGC API - Processes - Part 1: Core , created 2021-12-20
- [ ] 19. http://www.opengis.net/def/docs/12-128r18 OGC¬Æ GeoPackage Encoding Standard , created 2021-11-16
- [ ] 20. http://www.opengis.net/def/docs/20-010 OGC City Geography Markup Language (CityGML) Part 1: Conceptual Model Standard , created 2021-09-13
- [ ] 21. http://www.opengis.net/def/docs/19-086r4 OGC API - Environmental Data Retrieval Standard , created 2021-08-13
- [ ] 22. http://www.opengis.net/def/docs/18-088 OGC SensorThings API Part 1: Sensing Version 1.1 , created 2021-08-04
- [ ] 23. http://www.opengis.net/def/docs/08-068r3 Web Coverage Processing Service (WCPS) Language Interface Standard , created 2021-06-15
- [ ] 24. http://www.opengis.net/def/docs/15-045r7 OGC MetOcean Application profile for WCS2.1: Part 0 MetOcean Metadata , created 2021-03-22
- [ ] 25. http://www.opengis.net/def/docs/15-108r3 OGC MetOcean Application profile for WCS2.1: Part 1 MetOcean GetCorridor Extension , created 2021-03-22
- [ ] 26. http://www.opengis.net/def/docs/17-086r3 OGC MetOcean Application profile for WCS2.1: Part 2 MetOcean GetPolygon Extension , created 2021-03-22
- [ ] 27. http://www.opengis.net/def/docs/16-007r5 Volume 11: OGC CDB Core Standard Conceptual Model , created 2021-02-26
- [ ] 28. http://www.opengis.net/def/docs/20-050 Volume 13: OGC CDB Rules for Encoding CDB Vector Data using GeoPackage (Normative, Optional Extension). , created 2021-02-26
- [ ] 29. http://www.opengis.net/def/docs/15-113r6 Volume 1: OGC CDB Core Standard: Model and Physical Data Store Structure , created 2021-02-26
- [ ] 30. http://www.opengis.net/def/docs/15-112r4 Volume 3: OGC CDB Terms and Definitions (Normative) , created 2021-02-26
- [ ] 31. http://www.opengis.net/def/docs/12-128r17 OGC¬Æ GeoPackage Encoding Standard , created 2021-02-04
- [ ] 32. http://www.opengis.net/def/docs/16-032r3 OGC WaterML 2: Part 4 - GroundWaterML 2 (GWML2) , created 2021-01-20
- [ ] 33. http://www.opengis.net/def/docs/19-011r4 OGC¬Æ IndoorGML 1.1 , created 2020-11-05
- [ ] 34. http://www.opengis.net/def/docs/18-058 OGC API - Features - Part 2: Coordinate Reference Systems by Reference , created 2020-11-02
- [ ] 35. http://www.opengis.net/def/docs/18-067r3 OGC Symbology Conceptual Model: Core Part , created 2020-10-15
- [ ] 36. http://www.opengis.net/def/docs/12-000r2 OGC SensorML: Model and XML Encoding Standard , created 2020-08-10
- [ ] 37. http://www.opengis.net/def/docs/19-045r3 OGC Moving Features Encoding Extension - JSON , created 2020-05-21
- [ ] 38. http://www.opengis.net/def/docs/17-047r1 OGC OpenSearch-EO GeoJSON(-LD) Response Encoding Standard , created 2020-04-27
- [ ] 39. http://www.opengis.net/def/docs/16-071r3 Time Ontology in OWL , created 2020-03-26
- [ ] 40. http://www.opengis.net/def/docs/17-003r2 OGC EO Dataset Metadata GeoJSON(-LD) Encoding Standard , created 2020-02-14
- [ ] 41. http://www.opengis.net/def/docs/13-026r8 OGC¬Æ OpenSearch Extension for Earth Observation , created 2019-11-25
- [ ] 42. http://www.opengis.net/def/docs/18-043r3 OGC Hierarchical Data Format Version 5 (HDF5¬Æ) Core Standard , created 2019-10-28
- [ ] 43. http://www.opengis.net/def/docs/17-069r3 OGC API - Features - Part 1: Core , created 2019-10-07
- [ ] 44. http://www.opengis.net/def/docs/17-083r2 OGC Two Dimensional Tile Matrix Set , created 2019-10-06
- [ ] 45. http://www.opengis.net/def/docs/19-008r4 OGC GeoTIFF Standard , created 2019-09-14
- [ ] 46. http://www.opengis.net/def/docs/18-010r7 Geographic information ‚Äî Well-known text representation of coordinate reference systems , created 2019-08-13
- [ ] 47. http://www.opengis.net/def/docs/18-073r2 OGC PipelineML Conceptual and Encoding Model Standard , created 2019-08-08
- [ ] 48. http://www.opengis.net/def/docs/16-079 Semantic Sensor Network Ontology , created 2019-07-10
- [ ] 49. http://www.opengis.net/def/docs/18-000 OGC GeoPackage Related Tables Extension , created 2019-05-08
- [ ] 50. http://www.opengis.net/def/docs/17-007r1 OGC Web Services Security , created 2019-01-28
- [ ] 51. http://www.opengis.net/def/docs/17-079r1 OGC SensorThings API Part 2 ‚Äì Tasking Core , created 2019-01-08
- [ ] 52. http://www.opengis.net/def/docs/16-007r4 Volume 11: OGC CDB Core Standard Conceptual Model , created 2018-12-19
- [ ] 53. http://www.opengis.net/def/docs/15-113r5 Volume 1: OGC CDB Core Standard: Model and Physical Data Store Structure , created 2018-12-19
- [ ] 54. http://www.opengis.net/def/docs/15-112r3 Volume 3: OGC CDB Terms and Definitions , created 2018-12-19
- [ ] 55. http://www.opengis.net/def/docs/15-042r5 OGC TimeseriesML 1.2 ‚Äì XML Encoding of the Timeseries Profile of Observations and Measurements , created 2018-12-18
- [ ] 56. http://www.opengis.net/def/docs/16-060r2 OGC GML Application Schema ‚Äì Coverages : GRIB2 Coverage Encoding Profile , created 2018-11-27
- [ ] 57. http://www.opengis.net/def/docs/10-140r2 OGC¬Æ Web Coverage Service 2.0 Interface Standard - Earth Observation Application Profile , created 2018-10-04
- [ ] 58. http://www.opengis.net/def/docs/17-080r2 CDB Multi-Spectral Imagery Extension , created 2018-09-20
- [ ] 59. http://www.opengis.net/def/docs/08-085r8 OGC¬Æ GML in JPEG 2000 (GMLJP2) Encoding Standard , created 2018-08-27
- [ ] 60. http://www.opengis.net/def/docs/17-089r1 OGC Web Coverage Service (WCS) 2.1 Interface Standard - Core , created 2018-08-16
- [ ] 61. http://www.opengis.net/def/docs/17-066r1 OGC GeoPackage Extension for Tiled Gridded Coverage Data , created 2018-03-07
- [ ] 62. http://www.opengis.net/def/docs/14-111r6 OGC¬Æ WaterML 2: Part 3 - Surface Hydrology Features (HY_Features) - Conceptual Model , created 2018-01-08
- [ ] 63. http://www.opengis.net/def/docs/16-079 Semantic Sensor Network Ontology , created 2017-09-23
- [ ] 64. http://www.opengis.net/def/docs/16-107r2 OGC InfraGML 1.0: Part 7 ‚Äì LandInfra Land Division - Encoding Standard , created 2017-09-22
- [ ] 65. http://www.opengis.net/def/docs/09-146r6 OGC Coverage Implementation Schema , created 2017-09-15
- [ ] 66. http://www.opengis.net/def/docs/15-001r4 OGC¬Æ 3D Portrayal Service 1.0 , created 2017-09-13
- [ ] 67. http://www.opengis.net/def/docs/12-128r14 OGC¬Æ GeoPackage Encoding Standard , created 2017-08-25
- [ ] 68. http://www.opengis.net/def/docs/16-100r2 OGC InfraGML 1.0: Part 0 ‚Äì LandInfra Core - Encoding Standard , created 2017-08-16
- [ ] 69. http://www.opengis.net/def/docs/16-101r2 OGC InfraGML 1.0: Part 1 ‚Äì LandInfra Land Features - Encoding Standard , created 2017-08-16
- [ ] 70. http://www.opengis.net/def/docs/16-102r2 OGC InfraGML 1.0: Part 2 - LandInfra Facilities and Projects - Encoding Standard , created 2017-08-16
- [ ] 71. http://www.opengis.net/def/docs/16-103r2 OGC InfraGML 1.0: Part 3 - Alignments - Encoding Standard , created 2017-08-16
- [ ] 72. http://www.opengis.net/def/docs/16-104r2 OGC InfraGML 1.0: Part 4 - LandInfra Roads - Encoding Standard , created 2017-08-16
- [ ] 73. http://www.opengis.net/def/docs/16-105r2 OGC InfraGML 1.0: Part 5 - Railways - Encoding Standard , created 2017-08-16
- [ ] 74. http://www.opengis.net/def/docs/16-106r2 OGC InfraGML 1.0: Part 6 ‚Äì LandInfra Survey - Encoding Standard , created 2017-08-16
- [ ] 75. http://www.opengis.net/def/docs/16-083r2 OGC Coverage Implementation Schema - ReferenceableGridCoverage Extension , created 2017-06-15
- [ ] 76. http://www.opengis.net/def/docs/14-055r2 OGC OWS Context GeoJSON Encoding Standard , created 2017-04-07
- [ ] 77. http://www.opengis.net/def/docs/16-120r3 OGC Moving Features Access , created 2017-03-12
- [ ] 78. http://www.opengis.net/def/docs/16-032r2 OGC WaterML 2: Part 4 ‚Äì GroundWaterML 2 (GWML2) , created 2017-03-06
- [ ] 79. http://www.opengis.net/def/docs/16-007r3 Volume 11: OGC CDB Core Standard Conceptual Model , created 2017-02-23
- [ ] 80. http://www.opengis.net/def/docs/15-113r3 Volume 1: OGC CDB Core Standard: Model and Physical Data Store Structure , created 2017-02-23
- [ ] 81. http://www.opengis.net/def/docs/15-112r2 Volume 3: OGC CDB Terms and Definitions , created 2017-02-23
- [ ] 82. http://www.opengis.net/def/docs/16-008 OGC Geoscience Markup Language 4.1 (GeoSciML) , created 2017-01-31
- [ ] 83. http://www.opengis.net/def/docs/16-008r1 OGC Geoscience Markup Language 4.1 (GeoSciML) - with Corrigendum , created 2017-01-31
- [ ] 84. http://www.opengis.net/def/docs/15-097r1 OGC¬Æ Geospatial User Feedback Standard: Conceptual Model , created 2016-12-22
- [ ] 85. http://www.opengis.net/def/docs/15-098r1 OGC¬Æ Geospatial User Feedback Standard: XML Encoding Extension , created 2016-12-22
- [ ] 86. http://www.opengis.net/def/docs/15-111r1 OGC¬Æ Land and Infrastructure Conceptual Model Standard (LandInfra) , created 2016-12-20
- [ ] 87. http://www.opengis.net/def/docs/13-026r8 OGC¬Æ OpenSearch Extension for Earth Observation , created 2016-12-16
- [ ] 88. http://www.opengis.net/def/docs/13-057r1 OGC Web Coverage Service Interface Standard ‚Äì Transaction Extension , created 2016-11-17
- [ ] 89. http://www.opengis.net/def/docs/15-043r3 Timeseries Profile of Observations and Measurements  , created 2016-09-09
- [ ] 90. http://www.opengis.net/def/docs/15-042r3 TimeseriesML 1.0 ‚Äì XML Encoding of the Timeseries Profile of Observations and Measurements , created 2016-09-09
- [ ] 91. http://www.opengis.net/def/docs/13-131r1 OGC¬Æ Publish/Subscribe Interface Standard 1.0 - Core , created 2016-08-22
- [ ] 92. http://www.opengis.net/def/docs/13-133r1 OGC¬Æ Publish/Subscribe Interface Standard 1.0 SOAP Protocol Binding Extension , created 2016-08-22
- [ ] 93. http://www.opengis.net/def/docs/15-078r6 OGC SensorThings API Part 1: Sensing , created 2016-07-26
- [ ] 94. http://www.opengis.net/def/docs/12-168r6 OGC¬Æ Catalogue Services 3.0 - General Model , created 2016-06-10
- [ ] 95. http://www.opengis.net/def/docs/12-176r7 OGC¬Æ Catalogue Services 3.0 Specification - HTTP Protocol Binding , created 2016-06-10
- [ ] 96. http://www.opengis.net/def/docs/10-157r4 OGC¬Æ Earth Observation Metadata profile of Observations & Measurements , created 2016-06-09
- [ ] 97. http://www.opengis.net/def/docs/08-085r5 OGC GML in JPEG 2000 (GMLJP2) Encoding StandardPart 1: Core , created 2016-04-07
- [ ] 98. http://www.opengis.net/def/docs/15-018r2 OGC WaterML2.0: part 2 - Ratings, Gaugings and Sections , created 2016-02-03
- [ ] 99. http://www.opengis.net/def/docs/14-100r2 OGC¬Æ CF-netCDF 3.0 encoding using GML Coverage Application Schema , created 2015-11-18
- [ ] 100. http://www.opengis.net/def/docs/12-007r2 OGC KML 2.3 , created 2015-08-04
- [ ] 101. http://www.opengis.net/def/docs/12-128r12 OGC¬Æ GeoPackage Encoding Standard , created 2015-08-04
- [ ] 102. http://www.opengis.net/def/docs/12-128r12 OGC¬Æ GeoPackage Encoding Standard - With Corrigendum , created 2015-08-04
- [ ] 103. http://www.opengis.net/def/docs/12-128r12 OGC¬Æ GeoPackage Encoding Standard , created 2015-04-20
- [ ] 104. http://www.opengis.net/def/docs/12-128r12 OGC¬Æ GeoPackage Encoding Standard - With Corrigendum , created 2015-04-20
- [ ] 105. http://www.opengis.net/def/docs/14-065 OGC¬Æ WPS 2.0 Interface Standard , created 2015-03-05
- [ ] 106. http://www.opengis.net/def/docs/12-132r4 OGC Augmented Reality Markup Language 2.0 (ARML 2.0) , created 2015-02-24
- [ ] 107. http://www.opengis.net/def/docs/14-084r2 OGC¬Æ Moving Features Encoding Extension: Simple Comma Separated Values (CSV) , created 2015-02-17
- [ ] 108. http://www.opengis.net/def/docs/14-083r2 OGC¬Æ Moving Features Encoding Part I: XML Core , created 2015-02-17
- [ ] 109. http://www.opengis.net/def/docs/14-005r3 OGC¬Æ IndoorGML , created 2014-12-02
- [ ] 110. http://www.opengis.net/def/docs/08-085r4 OGC¬Æ GML in JPEG 2000 (GMLJP2) Encoding Standard Part 1: Core  , created 2014-09-23
- [ ] 111. http://www.opengis.net/def/docs/09-025r2 OGC¬Æ Web Feature Service 2.0 Interface Standard - With Corrigendum , created 2014-07-10
- [ ] 112. http://www.opengis.net/def/docs/12-100r1 OGC¬Æ GML Application Schema - Coverages - GeoTIFF Coverage Encoding Profile , created 2014-05-28
- [ ] 113. http://www.opengis.net/def/docs/11-014r3 OGC Open Modelling Interface Interface Standard , created 2014-05-26
- [ ] 114. http://www.opengis.net/def/docs/10-032r8 OGC¬Æ OpenSearch Geo and Time Extensions , created 2014-04-14
- [ ] 115. http://www.opengis.net/def/docs/10-126r4 OGC¬Æ WaterML 2.0: Part 1- Timeseries , created 2014-02-24
- [ ] 116. http://www.opengis.net/def/docs/12-128r10 OGC¬Æ GeoPackage Encoding Standard , created 2014-02-10
- [ ] 117. http://www.opengis.net/def/docs/12-000 OGC¬Æ SensorML: Model and XML Encoding Standard , created 2014-02-04
- [ ] 118. http://www.opengis.net/def/docs/12-080r2 OGC OWS Context Conceptual Model , created 2014-01-22
- [ ] 119. http://www.opengis.net/def/docs/12-084r2 OGC OWS Context Atom Encoding Standard , created 2014-01-14
- [ ] 120. http://www.opengis.net/def/docs/11-165r2 CF-netCDF3 Data Model Extension standard , created 2013-01-03
- [ ] 121. http://www.opengis.net/def/docs/11-038R2 OGC Network Common Data Form (NetCDF) NetCDF Enhanced Data Model Extension Standard , created 2012-10-02
- [ ] 122. http://www.opengis.net/def/docs/09-110r4 OGC¬Æ WCS 2.0 Interface Standard- Core:  Corrigendum  , created 2012-07-12
- [ ] 123. http://www.opengis.net/def/docs/11-052r4 OGC GeoSPARQL - A Geographic Query Language for RDF Data , created 2012-06-12
- [ ] 124. http://www.opengis.net/def/docs/12-006 OGC¬Æ Sensor Observation Service Interface Standard , created 2012-04-20
- [ ] 125. http://www.opengis.net/def/docs/12-019 OGC City Geography Markup Language (CityGML) Encoding Standard , created 2012-04-04
- [ ] 126. http://www.opengis.net/def/docs/10-129r1 OGC¬Æ Geography Markup Language (GML) - Extended schemas and encoding rules , created 2012-02-07
- [ ] 127. http://www.opengis.net/def/docs/09-127r2 OGC¬Æ PUCK Protocol Standard  , created 2012-01-25
- [ ] 128. http://www.opengis.net/def/docs/11-030r1 OGC¬Æ: Open GeoSMS Standard - Core , created 2012-01-19
- [ ] 129. http://www.opengis.net/def/docs/06-141r6 Ordering Services Framework for Earth Observation Products  Interface Standard , created 2012-01-09
- [ ] 130. http://www.opengis.net/def/docs/06-103r4 OpenGIS Implementation Specification for Geographic information - Simple feature access - Part 1: Common architecture , created 2011-05-28
- [ ] 131. http://www.opengis.net/def/docs/11-017 Geospatial eXtensible Access Control Markup Language (GeoXACML) Version 1 Corrigendum , created 2011-05-12
- [ ] 132. http://www.opengis.net/def/docs/09-083r3 GeoAPI 3.0 Implementation Standard , created 2011-04-25
- [ ] 133. http://www.opengis.net/def/docs/10-090r3 OGC Network Common Data Form (NetCDF)  Core Encoding Standard version 1.0 , created 2011-04-05
- [ ] 134. http://www.opengis.net/def/docs/09-000 OGC¬Æ Sensor Planning Service Implementation Standard , created 2011-03-28
- [ ] 135. http://www.opengis.net/def/docs/10-025r1 Observations and Measurements - XML Implementation , created 2011-03-22
- [ ] 136. http://www.opengis.net/def/docs/09-001 OpenGIS¬Æ SWE Service Model Implementation Standard , created 2011-03-21
- [ ] 137. http://www.opengis.net/def/docs/08-094r1 OGC¬Æ SWE Common Data Model Encoding Standard , created 2011-01-04
- [ ] 138. http://www.opengis.net/def/docs/09-026r1 OpenGIS Filter Encoding 2.0 Encoding Standard , created 2010-11-22
- [ ] 139. http://www.opengis.net/def/docs/10-070r2 OpenGIS¬Æ Georeferenced Table Joining Service Implementation Standard , created 2010-11-22
- [ ] 140. http://www.opengis.net/def/docs/09-148r1 OGC¬Æ Web Coverage Service 2.0 Interface Standard - XML/POST Protocol Binding Extension , created 2010-10-27
- [ ] 141. http://www.opengis.net/def/docs/09-149r1 OGC¬Æ Web Coverage Service 2.0 Interface Standard - XML/SOAP Protocol Binding Extension , created 2010-10-27
- [ ] 142. http://www.opengis.net/def/docs/06-104r4 OpenGIS Implementation Specification for Geographic information - Simple feature access - Part 2: SQL option , created 2010-08-04
- [ ] 143. http://www.opengis.net/def/docs/06-121r9 OGC Web Service Common Implementation Specification , created 2010-04-07
- [ ] 144. http://www.opengis.net/def/docs/07-057r7 OpenGIS Web Map Tile Service Implementation Standard , created 2010-04-06
- [ ] 145. http://www.opengis.net/def/docs/06-131r6 OGC¬Æ Catalogue Services Standard 2.0 Extension Package for ebRIM Application Profile: Earth Observation Products , created 2010-02-10
- [ ] 146. http://www.opengis.net/def/docs/08-068r2 OpenGIS Web Coverage Processing Service (WCPS) Language Interface Standard , created 2009-03-25
- [ ] 147. http://www.opengis.net/def/docs/08-059r3 OpenGIS Web Coverage Service (WCS) - Processing Extension (WCPS) , created 2009-03-25
- [ ] 148. http://www.opengis.net/def/docs/07-110r4 CSW-ebRIM Registry Service - Part 1: ebRIM profile of CSW , created 2009-02-05
- [ ] 149. http://www.opengis.net/def/docs/07-144r4 CSW-ebRIM Registry Service - Part 2: Basic extension package , created 2009-02-05
- [ ] 150. http://www.opengis.net/def/docs/07-068r4 Web Coverage Service (WCS) - Transaction operation extension , created 2009-01-15
- [ ] 151. http://www.opengis.net/def/docs/06-024r4 OGC Location Services (OpenLS): Tracking Service Interface Standard , created 2008-09-08
- [ ] 152. http://www.opengis.net/def/docs/07-074 OpenGIS Location Service (OpenLS) Implementation Specification: Core Services , created 2008-09-08
- [ ] 153. http://www.opengis.net/def/docs/08-028r7 OpenGIS Location Services (OpenLS): Part 6 - Navigation Service , created 2008-09-04
- [ ] 154. http://www.opengis.net/def/docs/08-007r1 OpenGIS¬Æ  City Geography Markup Language (CityGML) Encoding Standard , created 2008-08-20
- [ ] 155. http://www.opengis.net/def/docs/07-147r2 OGC KML , created 2008-04-14
- [ ] 156. http://www.opengis.net/def/docs/07-098r1 GeoXACML Implementation Specification - Extension A (GML2) Encoding , created 2008-02-23
- [ ] 157. http://www.opengis.net/def/docs/07-099r1 GeoXACML Implementation Specification - Extension B (GML3) Encoding , created 2008-02-23
- [ ] 158. http://www.opengis.net/def/docs/06-009r6 OpenGIS Sensor Observation Service , created 2008-02-13
- [ ] 159. http://www.opengis.net/def/docs/07-036 OpenGIS Geography Markup Language (GML) Encoding Standard , created 2007-10-05
- [ ] 160. http://www.opengis.net/def/docs/05-007r7 Web Processing Service , created 2007-10-05
- [ ] 161. http://www.opengis.net/def/docs/05-078r4 OpenGIS Styled Layer Descriptor Profile of the Web Map Service Implementation Specification , created 2007-08-14
- [ ] 162. http://www.opengis.net/def/docs/07-000 OpenGIS Sensor Model Language (SensorML) , created 2007-07-24
- [ ] 163. http://www.opengis.net/def/docs/07-006r1 OpenGIS Catalogue Service Implementation Specification , created 2007-04-20
- [ ] 164. http://www.opengis.net/def/docs/06-121r3 OpenGIS Web Service Common Implementation Specification , created 2007-04-03
- [ ] 165. http://www.opengis.net/def/docs/05-077r4 OpenGIS Symbology Encoding Implementation Specification , created 2007-01-18
- [ ] 166. http://www.opengis.net/def/docs/06-042 OpenGIS Web Map Service (WMS) Implementation Specification , created 2006-03-15
- [ ] 167. http://www.opengis.net/def/docs/05-047r3 OpenGIS GML in JPEG 2000 for Geographic Imagery  Encoding Specification , created 2006-01-20
- [ ] 168. http://www.opengis.net/def/docs/04-094 OpenGIS Web Feature Service (WFS) Implementation Specification , created 2005-05-03
- [ ] 169. http://www.opengis.net/def/docs/05-005 OpenGIS Web Map Context Implementation Specification , created 2005-05-03
- [ ] 170. http://www.opengis.net/def/docs/01-009 Coordinate Transformation Services - OLE/COM , created 2001-01-12
- [ ] 171. http://www.opengis.net/def/docs/01-009 OpenGIS Coordinate Transformation Service Implementation Specification , created 2001-01-12
- [ ] 172. http://www.opengis.net/def/docs/99-054 OpenGIS Simple Features Implementation Specification for CORBA , created 1999-06-02
- [ ] 173. http://www.opengis.net/def/docs/99-050 OpenGIS Simple Features Implementation Specification for OLE/COM , created 1999-05-18

**Comment by rob-metalinkage** [comment]
We have a proposal in development to split the building block register into subregisters based on maturity and governance of each.  

In general, building blocks should have unit tests and examples, so will need to be incrementally developed driven by upstream re-use demands or active SWG processes.

If neededed a batch draft extraction could be attempted and isolated in a special sub register of stubs, ready for testing.  We'd need to complete conformance class extraction first.  You could modify the SPARQL to only list standards with identified conformance classes.

**Comment by rob-metalinkage** [comment]
@ghobona could you please remove the results and put them in a file linked from the issue - it becomes unwieldy in a discussion thread to have it inline!  I'll leave it to you so its a machine readable file.

**Comment by ghobona** [comment]
Changing approach. Instead of listing all documents in a single GitHub Issue, I will create a 'publications-in-year per GitHub Issue'.

Closing this GitHub Issue as a result.
