### ISSUE TITLE
Which license should this project have?

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/bblocks#5]
I added an MIT license for the software - is that appropriated for the building blocks register? 
Should the building blocks live somewhere else, separated from the code?

**Comment by chris-little** [comment]
@doublebyte1 Why an MIT Licence? Why not a Creative Commons Licence, which may have wider acceptance on the Web?

**Comment by doublebyte1** [comment]
@chris-little although CC is good for content on the web, it lacks some specific information about software like what to do with the source code or patents. I am open to use any license from the Free Software Foundation or Open Source Initiative which specify these aspects.
