### ISSUE TITLE
Where should we place the link to the building block description?

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/bblocks#6]
Should it be on the title, or on the details? (see picture bellow)

![details](https://user-images.githubusercontent.com/1038897/209947370-17f23486-d17f-4a78-8330-5bec54910e08.png)

**Comment by chris-little** [comment]
@doublebyte1 Keep It Simple Surely? On the Title, because there may be other lower levels beside `Details`, such as `History` or `More`, etc. and each could have a different separate link.
